### ISSUE TITLE
Good job! I have some problem about randomly generating camera parameters during warping

### ISSUE THREAD

**Issue by DD20-dai** [yxuhan/AdaMPI#21]
Thank you for your great work !
I noticed that during the training of the given demo, we only perform random displacements on the X-axis but not random rotations or translations on the y or z-axis. In theory, the latter should make the network more robust?
Why did we choose to warp only on the X-axis? Is it because the latter is more difficult to train?
![ada1](https://github.com/yxuhan/AdaMPI/assets/59754610/f7ce357d-2ee9-4f77-9e4e-a00f1d30be07)
![ada2](https://github.com/yxuhan/AdaMPI/assets/59754610/a89b2498-8f4b-48b9-8458-035415cfa5b2)
![ada3](https://github.com/yxuhan/AdaMPI/assets/59754610/631f9654-905b-4ea9-8677-2b609483553b)

**Comment by yxuhan** [comment]
Hi, thanks for your interest in our work. 

Actually, we do not want to synthesize pseudo novel views far away from the source view during training. The reason is that MPI cannot represent out-of-frustum contents. At test time, we also keep the assumption that the users would like to use our model to synthesize novel views within a small range, like the 3D photo shown on our project page. So we let the warp operation only on the X-axis to limit the view range. 

We have not tried to introduce warp in the Y-axis or Z-axis during training.

**Comment by DD20-dai** [comment]
OK, I see.
Thanks for your reply!
