### ISSUE TITLE
about depth input

### ISSUE THREAD

**Issue by farmingyard** [yxuhan/AdaMPI#5]
hi han,

Thank you for your good job! 
I want to know how you get your sample depth map? I run DPT model, but the result is different with yours. Waiting for your reply. Thanks.

**Comment by yxuhan** [comment]
Hi @farmingyard, what kind of results have you got from DPT? I remember DPT would output a disparity map in 16-bit png format, and this is what we put in `warpback/toydata/dpt_depth`. In our code, we convert it to a depth map.

**Comment by farmingyard** [comment]
I mean the data in images/depth/,  such as below image,  the left is you provided，the right is I get from DPT large model. We can see that your depth seems doing some post-process, such as matting, so I am confused.
![image](https://user-images.githubusercontent.com/16593871/190974329-ea2cac69-2f24-460c-a17d-70963413cf7f.png)

**Comment by yxuhan** [comment]
This photo is taken from the high-resolution Div-2K dataset, we use [BoostDepth](https://github.com/compphoto/BoostingMonocularDepth) to refine the initial disparity map output by MiDaS (because BoostDepth does not support DPT at that time). For other low-resolution images, e.g. images in COCO dataset, we directly use the DPT estimation.

**Comment by farmingyard** [comment]
OK, I see. 
Thank you again~
