### ISSUE TITLE
Scale Issue

### ISSUE THREAD

**Issue by jiadingfang** [yxuhan/AdaMPI#6]
Hi,

Thanks for the great work!

I would like to reproduce some of the numbers reported in the paper. But I had an issue with handling the scale because depth from DPT are normalized, so using poses from the dataset that has real world scales always outputs synthesized images that are very off. Could you elaborate on how do you handle the scale issue in training and testing?

Thanks!

**Comment by yxuhan** [comment]
Hi, we only evaluate our method on the real-world dataset that provides multi-view image pairs. According to the SfM method like COLMAP, we can obtain camera parameters and some sparse 3D points in the scene from these multi-view image pairs.

Note these 3D points and camera parameters are on the same scale because they are reconstructed from the same SfM system. We then use some method like DPT to estimate a dense depth map for each view and then align its scale with the reconstructed 3D points. This way, the depth map and camera parameter are (roughly) on the same scale.

In practice, after align the scale of DPT disparity map to the camera parameters, we need an extra step to normalize the camera extrinsics and DPT depth map so that the DPT disparity map is in the range of [0,1].

**Comment by jiadingfang** [comment]
Thanks so much for replying!

I tried to follow the procedure you suggested as the following:

1. Get depth maps from certain number of COLMAP points in the source view
2. Get output from DPT for the source RGB image. Since I'm using `dpt_hybrid` DPT mode type, the output of DPT is actually normalized disparity. But it is hard to align COLMAP depths with this quantity, I choose to output original depth in extra from DPT.
3. Find the best affine approximation (shift and scale) between COLMAP depth and DPT depth.
4. Scale the translation vector in COLMAP pose as `t=t/scale`, according to [MINE](https://arxiv.org/pdf/2103.14910.pdf) section 3.3.1.

But I'm still not able to get decent test PSNR numbers from this scaled pose. My guess is it's because I'm not exactly sure what you mean by 

> "we need an extra step to normalize the camera extrinsics and DPT depth map so that the DPT disparity map is in the range of [0,1]."

I would greatly appreciate it if you could elaborate a bit more.

**Comment by yxuhan** [comment]
What about the results if you directly warp the source view to the target view using the aligned DPT depth map by your pipeline? Does the warped image aligned with the ground truth target view? You can use this strategy to check whether the DPT depth map is aligned with the camera parameters.
